### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ssnjr2002** [OliverSwift/Promys#2]
Hi, I would like to contribute to this project by designing a logo for it. Would you like to have a logo?

**Comment by OliverSwift** [comment]
Hey

Sure ! You’re very welcome 😁

-Olivier

**Comment by ssnjr2002** [comment]
Great! I will get started on that logo then :) 
My discord (if you are on discord and wants to contact me in some other way): @ssnjrthegr8#6263 and -
my email: ssnjr2002@gmail.com

**Comment by ssnjr2002** [comment]
How does these look?
![g2141](https://user-images.githubusercontent.com/38104354/38683248-a0d1ebb2-3e8a-11e8-9017-ee0b52a92104.png)
![rect2450](https://user-images.githubusercontent.com/38104354/38683250-a13261c2-3e8a-11e8-9ea2-c212a1b4f416.png)
![g2023](https://user-images.githubusercontent.com/38104354/38683252-a17615b6-3e8a-11e8-9353-98718dadeb87.png)

Logo idea: Raspberry + "screencasting waves" 
If you want a custom color scheme or any other changes just say and I will do it :+1:

**Comment by OliverSwift** [comment]
Promising! :)
If I may, base font is Gruppo (avail at Google Fonts), I love the waves idea, make it more obvious. I find the strawberry way too big, the two ideas (waves and fruit) are unbalanced.
Logo will eventually be the app icon. Details may fade away when scaled down.
I like the gradient you set up on PROMYS on the first proposal, it's subtil.
Keep up the good work

**Comment by ssnjr2002** [comment]
![g3806](https://user-images.githubusercontent.com/38104354/38718522-0f99a190-3f0b-11e8-841c-3dfe538b66fe.png)
![g3728](https://user-images.githubusercontent.com/38104354/38718526-0fe1e112-3f0b-11e8-987b-0e8cd0adfbc3.png)
![g3767](https://user-images.githubusercontent.com/38104354/38718529-102e4624-3f0b-11e8-83df-34b180c36e97.png)

How does it look now? Is the fruit looking symmetrical now? I have used your font and I must say it looks better now :) good choice. I think the waves are more obvious now. Tried making it even more obvious but then it just ruins the aesthetic appeal of the logo

**Comment by ValentinDebon** [comment]
I also find the idea very interesting. Colors and gradients add an amazing feel. But i wanted to say that if the logo will be embedded into app icons the raspberry may be rounder, just like the raspberry foundation logo. I love everything else by the way!

**Comment by ssnjr2002** [comment]
![g2904](https://user-images.githubusercontent.com/38104354/38764641-943b15e4-3fd0-11e8-8e99-078be0f6b69f.png)

How does this look then? This thing is distinguishable even at 32x32

**Comment by ssnjr2002** [comment]
Um, guys? Any feedback?

**Comment by OliverSwift** [comment]
Sorry :) Had to update stuff on the project.

You're almost there. The raspberry is too big IMHO and the "antenna" too small. I love the **first version of the two tips with waves on one of them**.
When I was referring to unbalanced things I was talking about the relative size between the fruit and the antennas.

From my point of view, your idea of the 2 tips with waves if the killing idea. Emphasize it :)

**Comment by ssnjr2002** [comment]
![g7321](https://user-images.githubusercontent.com/38104354/38884186-6d14242e-428c-11e8-883b-8f767bdd9efa.png)
So, how does this look?

**Comment by ssnjr2002** [comment]
![g7922](https://user-images.githubusercontent.com/38104354/38884303-dcaa7efa-428c-11e8-8af0-019331dccc4e.png)
Or this?

**Comment by OliverSwift** [comment]
Hey,

Yeah I like this one very much.
So you agree to distribute it under CC or BSD-3 ?

  -Olivier

**Comment by ssnjr2002** [comment]
Sorry for the late reply :grin: Would CC 4.0 be enough? Also was it the first one or the second you liked the most?

**Comment by OliverSwift** [comment]
Don't ask, it's your call :)
I've integrated it as icon in applications (a bit reworked for contour enhancement) and used it as is on main page.
Ok for CC4.0 I'll mention in the README.md

Cheers

**Comment by ssnjr2002** [comment]
Well, I have finalised the design and all the files can be obtained here: https://drive.google.com/open?id=16Ve70seAqDvS3wJ6eIzk-ftsENFa4y57. If you want any modifications feel free to ping me :) It was nice working with you. See ya!

**Comment by OliverSwift** [comment]
Likewise!
Thanks for the SVGs and PNGs. I'll update the splash screen with them.
Should I mention you as ssnjrthegr8 or do you have a friendlier pseudo? ;)

**Comment by ssnjr2002** [comment]
lol, just mention me as ssnjrthegr8
