### ISSUE TITLE
prebuilt binaries

### ISSUE THREAD

**Issue by cmpscabral** [OliverSwift/Promys#3]
Hi!
Do you plan on having pre-built, standalone binaries for the client?
Thanks!

**Comment by OliverSwift** [comment]
Hi Carlos,
It's already the case. You have the client binaries on the Promys device through the embedded web page.
Or available at http://promys.me for early commissioning. These are used when building SD image.

**Comment by cmpscabral** [comment]
yeah, my bad... thanks for clarifying :)
